// Generated by wxt
// Types for the #import virtual module
declare module '#imports' {
  export { browser, Browser } from 'wxt/browser';
  export { storage, StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage';
  export { useAppConfig } from 'wxt/utils/app-config';
  export { ContentScriptContext, WxtWindowEventMap } from 'wxt/utils/content-script-context';
  export { createIframeUi, IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe';
  export { createIntegratedUi, IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated';
  export { createShadowRootUi, ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root';
  export { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types';
  export { defineAppConfig, WxtAppConfig } from 'wxt/utils/define-app-config';
  export { defineBackground } from 'wxt/utils/define-background';
  export { defineContentScript } from 'wxt/utils/define-content-script';
  export { defineUnlistedScript } from 'wxt/utils/define-unlisted-script';
  export { defineWxtPlugin } from 'wxt/utils/define-wxt-plugin';
  export { injectScript, ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script';
  export { InvalidMatchPattern, MatchPattern } from 'wxt/utils/match-patterns';
  export { useState, useCallback, useMemo, useEffect, useRef, useContext, useReducer } from 'react';
  export { fakeBrowser } from 'wxt/testing';
  export { ToolErrorBoundary } from '../components/ToolErrorBoundary';
  export { ToolErrorBoundary } from '../components/index';
  export { Button, ButtonProps } from '../components/ui/button';
  export { Card, CardHeader, CardFooter, CardTitle, CardAction, CardDescription, CardContent } from '../components/ui/card';
  export { Checkbox } from '../components/ui/checkbox';
  export { Input } from '../components/ui/input';
  export { Label } from '../components/ui/label';
  export { Slider, SliderProps } from '../components/ui/slider';
  export { Textarea } from '../components/ui/textarea';
  export { cn } from '../components/ui/utils';
  export { useChromeCookies } from '../hooks/useChromeCookies';
  export { useExtensionStorage } from '../hooks/useExtensionStorage';
  export { useKeyboardShortcuts, getShortcutDisplayText, KeyboardShortcut, KeyboardShortcuts } from '../hooks/useKeyboardShortcuts';
  export { useToolHistory, useToolHistoryStats } from '../hooks/useToolHistory';
  export { useToolState, useToolStateWithConfig } from '../hooks/useToolState';
}
