// Generated by wxt
export {}
declare global {
  const Button: typeof import('/Users/sunven/github/QHelper/components/ui/button').Button
  const Card: typeof import('/Users/sunven/github/QHelper/components/ui/card').Card
  const CardAction: typeof import('/Users/sunven/github/QHelper/components/ui/card').CardAction
  const CardContent: typeof import('/Users/sunven/github/QHelper/components/ui/card').CardContent
  const CardDescription: typeof import('/Users/sunven/github/QHelper/components/ui/card').CardDescription
  const CardFooter: typeof import('/Users/sunven/github/QHelper/components/ui/card').CardFooter
  const CardHeader: typeof import('/Users/sunven/github/QHelper/components/ui/card').CardHeader
  const CardTitle: typeof import('/Users/sunven/github/QHelper/components/ui/card').CardTitle
  const Checkbox: typeof import('/Users/sunven/github/QHelper/components/ui/checkbox').Checkbox
  const CompactToolLayout: typeof import('/Users/sunven/github/QHelper/components/index').CompactToolLayout
  const ContentScriptContext: typeof import('wxt/utils/content-script-context').ContentScriptContext
  const InlineErrorDisplay: typeof import('/Users/sunven/github/QHelper/components/ToolErrorDisplay').InlineErrorDisplay
  const InvalidMatchPattern: typeof import('wxt/utils/match-patterns').InvalidMatchPattern
  const KeyboardShortcutsProvider: typeof import('/Users/sunven/github/QHelper/components/KeyboardShortcutsHelp').KeyboardShortcutsProvider
  const MatchPattern: typeof import('wxt/utils/match-patterns').MatchPattern
  const SimpleToolLayout: typeof import('/Users/sunven/github/QHelper/components/index').SimpleToolLayout
  const Textarea: typeof import('/Users/sunven/github/QHelper/components/ui/textarea').Textarea
  const ToolCard: typeof import('/Users/sunven/github/QHelper/components/index').ToolCard
  const ToolContent: typeof import('/Users/sunven/github/QHelper/components/index').ToolContent
  const ToolDivider: typeof import('/Users/sunven/github/QHelper/components/index').ToolDivider
  const ToolErrorBoundary: typeof import('/Users/sunven/github/QHelper/components/ToolErrorBoundary').ToolErrorBoundary
  const ToolErrorDisplay: typeof import('/Users/sunven/github/QHelper/components/ToolErrorDisplay').ToolErrorDisplay
  const ToolHeader: typeof import('/Users/sunven/github/QHelper/components/index').ToolHeader
  const ToolHint: typeof import('/Users/sunven/github/QHelper/components/index').ToolHint
  const ToolInputArea: typeof import('/Users/sunven/github/QHelper/components/index').ToolInputArea
  const ToolLayout: typeof import('/Users/sunven/github/QHelper/components/index').ToolLayout
  const ToolOutputArea: typeof import('/Users/sunven/github/QHelper/components/index').ToolOutputArea
  const ToolSection: typeof import('/Users/sunven/github/QHelper/components/index').ToolSection
  const browser: typeof import('wxt/browser').browser
  const cn: typeof import('/Users/sunven/github/QHelper/components/ui/utils').cn
  const createIframeUi: typeof import('wxt/utils/content-script-ui/iframe').createIframeUi
  const createIntegratedUi: typeof import('wxt/utils/content-script-ui/integrated').createIntegratedUi
  const createShadowRootUi: typeof import('wxt/utils/content-script-ui/shadow-root').createShadowRootUi
  const defineAppConfig: typeof import('wxt/utils/define-app-config').defineAppConfig
  const defineBackground: typeof import('wxt/utils/define-background').defineBackground
  const defineContentScript: typeof import('wxt/utils/define-content-script').defineContentScript
  const defineUnlistedScript: typeof import('wxt/utils/define-unlisted-script').defineUnlistedScript
  const defineWxtPlugin: typeof import('wxt/utils/define-wxt-plugin').defineWxtPlugin
  const fakeBrowser: typeof import('wxt/testing').fakeBrowser
  const getShortcutDisplayText: typeof import('/Users/sunven/github/QHelper/hooks/useKeyboardShortcuts').getShortcutDisplayText
  const injectScript: typeof import('wxt/utils/inject-script').injectScript
  const storage: typeof import('wxt/utils/storage').storage
  const useAppConfig: typeof import('wxt/utils/app-config').useAppConfig
  const useCallback: typeof import('react').useCallback
  const useChromeCookies: typeof import('/Users/sunven/github/QHelper/hooks/useChromeCookies').useChromeCookies
  const useContext: typeof import('react').useContext
  const useEffect: typeof import('react').useEffect
  const useExtensionStorage: typeof import('/Users/sunven/github/QHelper/hooks/useExtensionStorage').useExtensionStorage
  const useKeyboardShortcuts: typeof import('/Users/sunven/github/QHelper/hooks/useKeyboardShortcuts').useKeyboardShortcuts
  const useKeyboardShortcutsHelp: typeof import('/Users/sunven/github/QHelper/components/KeyboardShortcutsHelp').useKeyboardShortcutsHelp
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useToolErrorBoundary: typeof import('/Users/sunven/github/QHelper/components/ToolErrorBoundary').useToolErrorBoundary
  const useToolHistory: typeof import('/Users/sunven/github/QHelper/hooks/useToolHistory').useToolHistory
  const useToolHistoryStats: typeof import('/Users/sunven/github/QHelper/hooks/useToolHistory').useToolHistoryStats
  const useToolState: typeof import('/Users/sunven/github/QHelper/hooks/useToolState').useToolState
  const useToolStateWithConfig: typeof import('/Users/sunven/github/QHelper/hooks/useToolState').useToolStateWithConfig
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Browser } from 'wxt/browser'
  import('wxt/browser')
  // @ts-ignore
  export type { StorageArea, WxtStorage, WxtStorageItem, StorageItemKey, StorageAreaChanges, MigrationError } from 'wxt/utils/storage'
  import('wxt/utils/storage')
  // @ts-ignore
  export type { WxtWindowEventMap } from 'wxt/utils/content-script-context'
  import('wxt/utils/content-script-context')
  // @ts-ignore
  export type { IframeContentScriptUi, IframeContentScriptUiOptions } from 'wxt/utils/content-script-ui/iframe'
  import('wxt/utils/content-script-ui/iframe')
  // @ts-ignore
  export type { IntegratedContentScriptUi, IntegratedContentScriptUiOptions } from 'wxt/utils/content-script-ui/integrated'
  import('wxt/utils/content-script-ui/integrated')
  // @ts-ignore
  export type { ShadowRootContentScriptUi, ShadowRootContentScriptUiOptions } from 'wxt/utils/content-script-ui/shadow-root'
  import('wxt/utils/content-script-ui/shadow-root')
  // @ts-ignore
  export type { ContentScriptUi, ContentScriptUiOptions, ContentScriptOverlayAlignment, ContentScriptAppendMode, ContentScriptInlinePositioningOptions, ContentScriptOverlayPositioningOptions, ContentScriptModalPositioningOptions, ContentScriptPositioningOptions, ContentScriptAnchoredOptions, AutoMountOptions, StopAutoMount, AutoMount } from 'wxt/utils/content-script-ui/types'
  import('wxt/utils/content-script-ui/types')
  // @ts-ignore
  export type { WxtAppConfig } from 'wxt/utils/define-app-config'
  import('wxt/utils/define-app-config')
  // @ts-ignore
  export type { ScriptPublicPath, InjectScriptOptions } from 'wxt/utils/inject-script'
  import('wxt/utils/inject-script')
  // @ts-ignore
  export type { ToolErrorBoundary } from '/Users/sunven/github/QHelper/components/ToolErrorBoundary'
  import('/Users/sunven/github/QHelper/components/ToolErrorBoundary')
  // @ts-ignore
  export type { ButtonProps } from '/Users/sunven/github/QHelper/components/ui/button'
  import('/Users/sunven/github/QHelper/components/ui/button')
  // @ts-ignore
  export type { KeyboardShortcut, KeyboardShortcuts } from '/Users/sunven/github/QHelper/hooks/useKeyboardShortcuts'
  import('/Users/sunven/github/QHelper/hooks/useKeyboardShortcuts')
}
