// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/codebeautify.html"
    | "/colorTransform.html"
    | "/convert.html"
    | "/cron.html"
    | "/csstool.html"
    | "/csv2json.html"
    | "/htmlformat.html"
    | "/icons/q-128.png"
    | "/icons/q-16.png"
    | "/icons/q-48.png"
    | "/imagebase64.html"
    | "/json.html"
    | "/jsonschema.html"
    | "/libs/difflib.js"
    | "/libs/diffview.js"
    | "/markdown.html"
    | "/password.html"
    | "/pictureSplicing.html"
    | "/popup.html"
    | "/scss.html"
    | "/svgoptimizer.html"
    | "/timestamp.html"
    | "/toml.html"
    | "/trans-radix.html"
    | "/uglify.html"
    | "/urlparser.html"
    | "/uuid.html"
    | "/xmlformatter.html"
    | "/yaml.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
