// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/codebeautify.html"
    | "/colorTransform.html"
    | "/convert.html"
    | "/icons/q-128.png"
    | "/icons/q-16.png"
    | "/icons/q-48.png"
    | "/imagebase64.html"
    | "/json.html"
    | "/libs/difflib.js"
    | "/libs/diffview.js"
    | "/pictureSplicing.html"
    | "/popup.html"
    | "/timestamp.html"
    | "/trans-radix.html"
    | "/uglify.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
