// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/bookmarks.html"
    | "/content-scripts/dictionary.js"
    | "/content-scripts/github.js"
    | "/content-scripts/unpkg.js"
    | "/content-scripts/v2ex-base64.js"
    | "/content-scripts/web-summary.js"
    | "/devtools.html"
    | "/icons/q-128.png"
    | "/icons/q-16.png"
    | "/icons/q-48.png"
    | "/icons/zread-favicon.ico"
    | "/json-string-panel.html"
    | "/libs/difflib.js"
    | "/libs/diffview.js"
    | "/popup.html"
    | "/scss-worker.html"
    | "/sidepanel.html"
    | "/tools.html"
    | `/tools/${string}`
    | "/uglify-worker.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
