import type { ToolMetadata } from './ToolMetadata';
import { ToolCategory, ToolFeature, ToolStatus } from './ToolMetadata';

/**
 * 所有工具的注册列表
 *
 * 新增工具时，在此处添加工具元数据
 */
export const tools: ToolMetadata[] = [
  // ===== 常用工具 =====
  {
    id: 'json',
    name: 'JSON 格式化',
    nameEn: 'JSON Formatter',
    category: ToolCategory.COMMON,
    icon: 'Code',
    description: 'JSON 格式化、压缩、diff 对比',
    descriptionEn: 'Format, validate, and diff JSON data',
    keywords: ['json', '格式化', '解析', 'formatter', 'format'],
    tags: ['json', 'format', 'diff', 'validate'],
    entry: 'json.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.DUAL_INPUT, ToolFeature.HISTORY, ToolFeature.EXPORT, ToolFeature.COPY_RESULT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'trans-radix',
    name: '进制转换',
    nameEn: 'Radix Converter',
    category: ToolCategory.COMMON,
    icon: 'Calculator',
    description: '二进制、八进制、十进制、十六进制转换',
    descriptionEn: 'Convert between binary, octal, decimal, and hexadecimal',
    keywords: ['进制', '转换', '二进制', '十六进制', 'radix', 'base'],
    tags: ['convert', 'number', 'base', 'radix'],
    entry: 'trans-radix.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.REAL_TIME],
    status: ToolStatus.STABLE,
  },

  // ===== 编码转换 =====
  {
    id: 'convert',
    name: '字符串编解码',
    nameEn: 'String Encode/Decode',
    category: ToolCategory.ENCODING,
    icon: 'Code',
    description: 'Base64、URL、HTML 实体编解码',
    descriptionEn: 'Base64, URL, HTML entity encoding/decoding',
    keywords: ['编码', '解码', 'base64', 'url', 'encode', 'decode'],
    tags: ['encode', 'decode', 'base64', 'url', 'html'],
    entry: 'convert.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'codebeautify',
    name: '代码美化',
    nameEn: 'Code Beautify',
    category: ToolCategory.ENCODING,
    icon: 'Wand2',
    description: 'JavaScript/HTML/CSS 代码美化',
    descriptionEn: 'Beautify JavaScript, HTML, CSS code',
    keywords: ['美化', '格式化', '代码', 'beautify', 'format'],
    tags: ['code', 'beautify', 'format', 'js', 'html', 'css'],
    entry: 'codebeautify.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'uglify',
    name: '代码压缩',
    nameEn: 'Uglify',
    category: ToolCategory.ENCODING,
    icon: 'Zap',
    description: 'JavaScript 代码压缩混淆',
    descriptionEn: 'Minify and obfuscate JavaScript code',
    keywords: ['压缩', '混淆', 'uglify', 'minify'],
    tags: ['code', 'minify', 'compress', 'js'],
    entry: 'uglify.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  // ===== 图片工具 =====
  {
    id: 'imagebase64',
    name: '图片 Base64',
    nameEn: 'Image to Base64',
    category: ToolCategory.IMAGE,
    icon: 'Image',
    description: '图片转 Base64 编码',
    descriptionEn: 'Convert image to Base64 encoding',
    keywords: ['图片', 'base64', '转换', 'image', 'convert'],
    tags: ['image', 'base64', 'convert', 'png', 'jpg'],
    entry: 'imagebase64.html',
    version: '1.0.0',
    features: [ToolFeature.FILE_INPUT, ToolFeature.DRAG_DROP, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'pictureSplicing',
    name: '图片拼接',
    nameEn: 'Image Splicer',
    category: ToolCategory.IMAGE,
    icon: 'ImagePlus',
    description: '多张图片纵向/横向拼接',
    descriptionEn: 'Combine multiple images vertically or horizontally',
    keywords: ['图片', '拼接', '合并', 'image', 'splice', 'merge'],
    tags: ['image', 'splice', 'merge', 'combine'],
    entry: 'pictureSplicing.html',
    version: '1.0.0',
    features: [ToolFeature.FILE_INPUT, ToolFeature.DRAG_DROP, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  // ===== 其他工具 =====
  {
    id: 'timestamp',
    name: '时间戳转换',
    nameEn: 'Timestamp Converter',
    category: ToolCategory.OTHER,
    icon: 'CalendarClock',
    description: 'Unix 时间戳与日期时间互转',
    descriptionEn: 'Convert Unix timestamp to datetime and vice versa',
    keywords: ['时间戳', '日期', '转换', 'timestamp', 'date', 'time'],
    tags: ['time', 'timestamp', 'date', 'convert'],
    entry: 'timestamp.html',
    version: '1.0.0',
    features: [ToolFeature.REAL_TIME],
    status: ToolStatus.STABLE,
  },

  {
    id: 'colorTransform',
    name: '颜色转换',
    nameEn: 'Color Converter',
    category: ToolCategory.OTHER,
    icon: 'Palette',
    description: 'RGB、HEX、HSL 颜色格式转换',
    descriptionEn: 'Convert between RGB, HEX, HSL color formats',
    keywords: ['颜色', '转换', 'rgb', 'hex', 'hsl', 'color'],
    tags: ['color', 'convert', 'rgb', 'hex', 'hsl'],
    entry: 'colorTransform.html',
    version: '1.0.0',
    features: [ToolFeature.REAL_TIME],
    status: ToolStatus.STABLE,
  },

  // ===== 安全与加密 =====
  {
    id: 'uuid',
    name: 'UUID 生成器',
    nameEn: 'UUID Generator',
    category: ToolCategory.SECURITY,
    icon: 'Hash',
    description: '生成 UUID v4 标识符',
    descriptionEn: 'Generate UUID v4 identifiers',
    keywords: ['uuid', '生成', '标识符', 'id', 'guid'],
    tags: ['uuid', 'generator', 'id', 'identifier'],
    entry: 'uuid.html',
    version: '1.0.0',
    features: [ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'password',
    name: '密码生成器',
    nameEn: 'Password Generator',
    category: ToolCategory.SECURITY,
    icon: 'Key',
    description: '生成安全的随机密码',
    descriptionEn: 'Generate secure random passwords',
    keywords: ['密码', '生成', '安全', 'password', 'generator'],
    tags: ['password', 'generator', 'security', 'random'],
    entry: 'password.html',
    version: '1.0.0',
    features: [ToolFeature.COPY_RESULT, ToolFeature.REAL_TIME],
    status: ToolStatus.STABLE,
  },

  // ===== Web 格式 =====
  {
    id: 'markdown',
    name: 'Markdown 编辑器',
    nameEn: 'Markdown Editor',
    category: ToolCategory.WEB_FORMAT,
    icon: 'FileText',
    description: 'Markdown 实时预览、导出 HTML',
    descriptionEn: 'Real-time Markdown preview with HTML export',
    keywords: ['markdown', '编辑器', '预览', 'html', 'editor', 'preview'],
    tags: ['markdown', 'editor', 'preview', 'html', 'gfm'],
    entry: 'markdown.html',
    version: '1.0.0',
    features: [ToolFeature.DUAL_INPUT, ToolFeature.HISTORY, ToolFeature.EXPORT, ToolFeature.COPY_RESULT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'htmlformat',
    name: 'HTML 格式化器',
    nameEn: 'HTML Formatter',
    category: ToolCategory.WEB_FORMAT,
    icon: 'Code2',
    description: 'HTML 美化、压缩、格式化',
    descriptionEn: 'Beautify, minify, and format HTML code',
    keywords: ['html', '格式化', '美化', '压缩', 'format', 'beautify'],
    tags: ['html', 'format', 'beautify', 'minify', 'code'],
    entry: 'htmlformat.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'urlparser',
    name: 'URL 解析器',
    nameEn: 'URL Parser',
    category: ToolCategory.WEB_FORMAT,
    icon: 'Link2',
    description: '解析 URL 各个组成部分',
    descriptionEn: 'Parse URL components',
    keywords: ['url', '解析', 'parse', '链接'],
    tags: ['url', 'parser', 'link'],
    entry: 'urlparser.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.REAL_TIME, ToolFeature.COPY_RESULT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'csstool',
    name: 'CSS 工具',
    nameEn: 'CSS Tool',
    category: ToolCategory.WEB_FORMAT,
    icon: 'Palette',
    description: 'CSS 美化、压缩、优化',
    descriptionEn: 'Beautify, minify, and optimize CSS',
    keywords: ['css', '格式化', '美化', '压缩', 'format', 'beautify'],
    tags: ['css', 'format', 'beautify', 'minify', 'style'],
    entry: 'csstool.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'scss',
    name: 'SCSS 编译器',
    nameEn: 'SCSS Compiler',
    category: ToolCategory.WEB_FORMAT,
    icon: 'FileJson',
    description: 'SCSS/SASS 编译为 CSS',
    descriptionEn: 'Compile SCSS/SASS to CSS',
    keywords: ['scss', 'sass', '编译', 'css', 'compile'],
    tags: ['scss', 'sass', 'css', 'compile', 'preprocessor'],
    entry: 'scss.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'svgoptimizer',
    name: 'SVG 优化器',
    nameEn: 'SVG Optimizer',
    category: ToolCategory.WEB_FORMAT,
    icon: 'Image',
    description: 'SVG 优化、压缩、减小文件大小',
    descriptionEn: 'Optimize and compress SVG files',
    keywords: ['svg', '优化', '压缩', 'optimize', 'compress'],
    tags: ['svg', 'image', 'optimize', 'compress', 'vector'],
    entry: 'svgoptimizer.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.FILE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'cron',
    name: 'Cron 解析器',
    nameEn: 'Cron Parser',
    category: ToolCategory.DATA_FORMAT,
    icon: 'Clock',
    description: 'Cron 表达式解析、验证、计算运行时间',
    descriptionEn: 'Parse, validate, and calculate Cron expression schedules',
    keywords: ['cron', '表达式', '解析', '定时任务', 'schedule', 'parser'],
    tags: ['cron', 'schedule', 'parser', 'time', 'expression'],
    entry: 'cron.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  // ===== 数据格式 =====
  {
    id: 'csv2json',
    name: 'CSV 转 JSON',
    nameEn: 'CSV to JSON',
    category: ToolCategory.DATA_FORMAT,
    icon: 'FileJson',
    description: 'CSV 格式转换为 JSON 格式',
    descriptionEn: 'Convert CSV format to JSON format',
    keywords: ['csv', 'json', '转换', 'convert'],
    tags: ['csv', 'json', 'convert', 'format'],
    entry: 'csv2json.html',
    version: '1.0.0',
    features: [ToolFeature.FILE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'yaml',
    name: 'YAML 转换器',
    nameEn: 'YAML Converter',
    category: ToolCategory.DATA_FORMAT,
    icon: 'FileCode',
    description: 'YAML 与 JSON 格式互转',
    descriptionEn: 'Convert between YAML and JSON format',
    keywords: ['yaml', 'json', '转换', 'convert'],
    tags: ['yaml', 'json', 'convert', 'format'],
    entry: 'yaml.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.BETA,
  },

  {
    id: 'toml',
    name: 'TOML 解析器',
    nameEn: 'TOML Parser',
    category: ToolCategory.DATA_FORMAT,
    icon: 'FileJson',
    description: 'TOML ↔ JSON 转换、验证',
    descriptionEn: 'Convert between TOML and JSON format',
    keywords: ['toml', 'json', '转换', 'parse', 'config'],
    tags: ['toml', 'json', 'convert', 'config', 'parser'],
    entry: 'toml.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'jsonschema',
    name: 'JSON Schema 验证器',
    nameEn: 'JSON Schema Validator',
    category: ToolCategory.DATA_FORMAT,
    icon: 'Shield',
    description: '使用 JSON Schema 验证 JSON 数据结构',
    descriptionEn: 'Validate JSON data against JSON Schema',
    keywords: ['json', 'schema', '验证', 'validate', 'validation'],
    tags: ['json', 'schema', 'validate', 'validation', 'data'],
    entry: 'jsonschema.html',
    version: '1.0.0',
    features: [ToolFeature.DUAL_INPUT, ToolFeature.REAL_TIME, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },

  {
    id: 'xmlformatter',
    name: 'XML 格式化器',
    nameEn: 'XML Formatter',
    category: ToolCategory.DATA_FORMAT,
    icon: 'FileCode',
    description: 'XML 美化、压缩、格式化、验证',
    descriptionEn: 'Beautify, minify, format, and validate XML',
    keywords: ['xml', '格式化', '美化', '压缩', 'format', 'beautify', 'minify'],
    tags: ['xml', 'format', 'beautify', 'minify', 'validate'],
    entry: 'xmlformatter.html',
    version: '1.0.0',
    features: [ToolFeature.SINGLE_INPUT, ToolFeature.REAL_TIME, ToolFeature.COPY_RESULT, ToolFeature.EXPORT],
    status: ToolStatus.STABLE,
  },
];
